/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.timmson.invest.moex;

import org.junit.jupiter.api.Test;

import java.net.MalformedURLException;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MoexApiFactoryShould {


    @Test
    void returnApiForFiles() {
        final var localMoexApi = MoexApiFactory.createLocalMoexApi("some file");

        assertEquals(LocalMoexApi.class, localMoexApi.getClass());
    }


    @Test
    void returnApiForURLs() throws MalformedURLException {
        final var localRemoteApi = MoexApiFactory.createRemoteMoexApi("http://exmaple.org");

        assertEquals(RemoteMoexApi.class, localRemoteApi.getClass());
    }
}
